---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-trade-vbs-btc
  namespace: auto-trade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-trade-vbs-btc
  template:
    metadata:
      labels:
        app: auto-trade-vbs-btc
    spec:
      containers:
        - name: auto-trade-vbs-btc
          image: byun618/auto-trade
          resources:
            requests:
              cpu: "200m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
          env:
            - name: ALGORITHM
              value: vbs
            - name: TICKER
              value: KRW-BTC
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
